### ISSUE TITLE
[Security] google, 42 secret key가 노출되었는데 어떻게 할까요?

### ISSUE THREAD

**Issue by perman0519** [peer-42seoul/Peer-Backend#19]
1. 일단 놔둔다. 아직 oauth2로 뭘 하진 않았습니다.
2. 되돌릴 수 있으면 되돌린다
      2-1. 커밋을 삭제한다?

의견 부탁드립니다

**Comment by sinryuji** [comment]
노출되었다는게 코드상에 그대로 박혀있다는 뜻인가요?

**Comment by perman0519** [comment]
넵

**Comment by perman0519** [comment]
넵 이방법으로 하겠습니다 다음부턴 주의할게요
