### ISSUE TITLE
[FEATURE] nhn object storage 적용

### ISSUE THREAD

**Issue by weejihye** [peer-42seoul/Peer-Backend#224]
### Description
파일모듈에 nhn object storage 적용하기

### To-Do
- [ ] example

**Comment by Paul2021-R** [comment]
해당 내용 진행 전에, 구조 짜면 공유 먼저 부탁드립니다.

**Comment by weejihye** [comment]
> 해당 내용 진행 전에, 구조 짜면 공유 먼저 부탁드립니다.

- 넹~

**Comment by weejihye** [comment]
@joonseong11 님이 적용해주셔서 해당 이슈 닫겠습니다~
