### ISSUE TITLE
[BUG] QA 버그 리포트 : signup-code Authentication 요청?

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/Peer-Backend#247]
#### 문제 상황
<img width="1093" alt="스크린샷 2023-11-02 오후 5 12 19" src="https://github.com/peer-42seoul/Peer-Backend/assets/80471693/d9ae9fe4-a2b2-4493-8b4e-f322e558d002">

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : vivaldi

#### 사전 조건 (ex. 로그인 여부)
회원가입이 안되어 postman으로 직접 이메일 인증해봄

#### 예상 결과
이메일 인증 성공

#### 실제 결과
JWT 토큰 필요하다는 내용 나옴

#### 심각도
매우 심각, 핫픽스 필요, security 파트에 해당 API 등록 필요

**Comment by sinryuji** [comment]
api/v1/signup/code로 요청하셔야 돼요

**Comment by Paul2021-R** [comment]
안그래도 나중에 확인해보니 제 휴먼 이슈네요 이슈 닫습니다 ㅠ
