### ISSUE TITLE
[BUG] C-SIGN-04 OAuth 로그인 시도 시 json 객체가 보이는 현상

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Backend#249]
#### 문제 상황
OAuth 로그인 시도 시 401 에러와 함께 `{"message":"Full authentication is required to access this resource"}`라는 객체가 화면에 뜹니다.

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 하지 않음

#### 재현 절차
1. 로그인 페이지로 이동
2. OAuth 버튼 클릭

#### 예상 결과
구글 또는 42 로그인이 뜬다.

#### 실제 결과
아래와 같은 화면이 뜸
<img width="736" alt="스크린샷 2023-11-02 오후 7 17 32" src="https://github.com/peer-42seoul/Peer-Backend/assets/91731260/d6ab1170-d89f-4f60-8ab6-e8216c4bc891">

#### 심각도
상

**Comment by sinryuji** [comment]
수정되었습니다
