### ISSUE TITLE
[BUG] B-INFO 회원가입 시 비밀번호 유효검사 로직 수정 필요.

### ISSUE THREAD

**Issue by wochae** [peer-42seoul/Peer-Backend#251]
#### 문제 상황
![image](https://github.com/peer-42seoul/Peer-Backend/assets/101040879/a43398a0-e3a7-4d7f-9a26-042be562bf4f)

프론트에서 요청하는 requestBody : userInfo DTO에서 정상적으로 받아온 값으로 유저를 생성할 때,
password 는 해시 되어 저장되기 때문에, 20자를 넘어 정상 제출 임에도 오류를 반환합니다.

#### 테스트 환경
환경 무관
- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 재현 절차

유저 엔터티 비밀번호 글자 수 속성을 제거
![image](https://github.com/peer-42seoul/Peer-Backend/assets/101040879/99dcaaed-ae3c-40ec-ab63-7ea08d3eb262)

포스트맨으로 요청 시 200 상태코드를 받았고,
컨테이너 내 MySQL 터미널로 들어가 값을 확인했을 때,
![image](https://github.com/peer-42seoul/Peer-Backend/assets/101040879/26ddc28c-6c5a-4cd3-91b1-f232eea975c3)
비밀번호 값이 60자였습니다.
#### 심각도
上

**Comment by sinryuji** [comment]
수정했습니다!

**Comment by wochae** [comment]
<img width="1484" alt="image" src="https://github.com/peer-42seoul/Peer-Backend/assets/101040879/0c09148d-2fcf-4c6d-8627-d6d0426c685f">
확인 완료!
