### ISSUE TITLE
[BUG] 메인페이지 모집글 리스트 500에러

### ISSUE THREAD

**Issue by sinryuji** [peer-42seoul/Peer-Backend#252]
#### 문제 상황
메인 페이지 접근 시 모집글 리스트 API를 호출하는데 500에러 발생

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
없음

#### 재현 절차
메인 페이지 접속

#### 예상 결과
모집글 리스트를 불러온다.

#### 실제 결과
에러 발생

#### 심각도
중

**Comment by weejihye** [comment]
네 해당 상황 인지 했고 hotfix 올리겠습니다.
