### ISSUE TITLE
[BUG] B-INFO 중복된 이메일 처리

### ISSUE THREAD

**Issue by wochae** [peer-42seoul/Peer-Backend#253]
#### 문제 상황
이메일 인증 요청에 중복 이메일 검증 절차가 없음.
최종 제출 시 상태코드가 API 명세서와 다르게 반환.
에러 반환 조건문에 수정이 필요함.

#### 테스트 환경
- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 x

#### 재현 절차
이미 가입한 계정이 있는 상태에서 다시 같은 이메일로 회원가입 시도

#### 예상 결과
이메일 전송 시 중복 이메일 반환,
409 Conflict
#### 실제 결과
다음 페이지에 폼 전송 시 에러 반환,
401 Unauthorized
![image](https://github.com/peer-42seoul/Peer-Backend/assets/101040879/fa184524-8f46-4eb9-852e-6fee0006760b)
![image](https://github.com/peer-42seoul/Peer-Backend/assets/101040879/90f3e275-2cbd-4d62-b75d-624fe219d488)

#### 심각도
중

**Comment by sinryuji** [comment]
수정했습니다!

**Comment by wochae** [comment]
![image](https://github.com/peer-42seoul/Peer-Backend/assets/101040879/fae80842-b93a-464c-a84b-239df462a3f6)

확인!
