### ISSUE TITLE
[BUG] C-MYPAGE-37, 38 관심 리스트 페이지 접근 시 500 에러

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Backend#256]
#### 문제 상황
관심 리스트 페이지 접근 시 500 에러가 뜹니다.

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 된 상태

#### 재현 절차
1. 마이페이지 - 관심리스트 접근

##### request body
```json
    "type": project
    "page": 1
    "pagesize": 10
```

##### response body
```
failed to lazily initialize a collection of role: peer.backend.entity.user.User.recruitFavorites,
could not initialize proxy-no Session
```

#### 예상 결과
200, postList가 빈 배열 혹은 null로 들어온다.

#### 실제 결과
500 에러가 뜬다.

#### 심각도
상

**Comment by weejihye** [comment]
수정 완료
