### ISSUE TITLE
[BUG] J-TB- 모집 글쓰기 페이지 접속시 태그가 불러오지 않는 버그

### ISSUE THREAD

**Issue by juhyeonlee134** [peer-42seoul/Peer-Backend#296]
#### 문제 상황
<img width="492" alt="Screen Shot 2023-11-09 at 3 43 26 PM" src="https://github.com/peer-42seoul/Peer-Backend/assets/76419137/32615de1-122a-4d3e-9be5-8d3731b9459b">
<img width="451" alt="Screen Shot 2023-11-09 at 3 43 47 PM" src="https://github.com/peer-42seoul/Peer-Backend/assets/76419137/77698c32-829f-4f23-88e2-c8f3d98ce283">

#### 테스트 환경

- OS(mac / ipad / android...) : mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인을 해야함

#### 재현 절차
로그인을 하고 /recruitment/write에 접속

#### 예상 결과
오류 메시지가 나오지 않고, 작성가능해야 함

#### 실제 결과
태그를 불러오는데 실패 했다는 메세지가 뜸(다만 작성은 가능함). 오류 메시지는 다음과 같음
```
Failed to convert value of type 'java.lang.String'to required type 'java.lang.Long';nested exception is java.lang.NumberFormatException: For input string: "write"
```

#### 심각도
하

**Comment by weejihye** [comment]
해당 내용 dto 문제로 확인되어 해결 되었으므로 이슈 닫겠습니다.
