### ISSUE TITLE
[BUG] 데이터베이스 테이블 오류

### ISSUE THREAD

**Issue by wochae** [peer-42seoul/Peer-Backend#328]
#### 문제 상황
![image](https://github.com/peer-42seoul/Peer-Backend/assets/101040879/18be5477-fafe-453b-8a14-0ad513af86cb)
왼쪽은 원격 데이터베이스, 도커에서 생성한 데이터베이스입니다.
#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by Paul2021-R** [comment]
해결 완료
