### ISSUE TITLE
[BUG] FileService

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/Peer-Backend#451]
#### 문제 상황
[관련 내용 링크](https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&pullRequest=445&id=peer-42seoul_Peer-Backend)

#### 심각도
- 상

#### 내용 
- Sonar Cloud 기반으로 현재 있는 버그 대응할 것

**Comment by Paul2021-R** [comment]
Security Vulnerabilities 3건 추가로 있음 확인할 것

**Comment by weejihye** [comment]
로컬파일 저장쪽으로 현재 사용되지 않습니다. 삭제가 더 낫지 않을까요
