### ISSUE TITLE
[BUG] dnd에서 url로 다른 팀의 정보 조회 가능

### ISSUE THREAD

**Issue by weejihye** [peer-42seoul/Peer-Backend#542]
#### 문제 상황
dnd에서 url로 다른 팀의 정보가 불러와지는 상황
#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by Paul2021-R** [comment]
team 의 구성원 List에 들어있는 사람에 대해서만 접근 가능하도록 수정함.
