### ISSUE TITLE
[BUG] 팀 생성 시 지원자 목록에 들어가는 현상

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Backend#551]
#### 문제 상황

<img width="941" alt="image" src="https://github.com/peer-42seoul/Peer-Backend/assets/54823522/0b40ea32-eb2b-4216-ae9d-b83cccb799d4">

팀 생성한 사람이 지원자 목록에 들어가는 현상

#### 테스트 환경

- OS(mac / ipad / android...) : macos
- 웹 브라우저 : 크롬

#### 사전 조건 (ex. 로그인 여부)

- 로그인 필요
- 팀 생성 필요

#### 예상 결과

글 생성자는 지원자 목록에 없어야 합니다

#### 심각도

8 / 10

**Comment by weejihye** [comment]
지원자에서 제외 하도록 로직 추가하겠습니다.

**Comment by weejihye** [comment]
픽스 종료되었습니다. 이슈 닫겠습니다~
