### ISSUE TITLE
[BUG] 지원자 목록에 있는 분들이 승인 없이도 팀원이 되어 버림

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Backend#552]
#### 문제 상황

<img width="941" alt="image" src="https://github.com/peer-42seoul/Peer-Backend/assets/54823522/4860f769-ef82-4a15-91f0-5c8eed0e5a93">

놀랍게도 위 사진에 있는 모두, 승인 없이 팀원이 되었습니다.

#### 테스트 환경

- OS(mac / ipad / android...) : macos
- 웹 브라우저 : 크롬

#### 사전 조건 (ex. 로그인 여부)

- 로그인
- 팀 생성
- 다른 사람들의 지원 필요

#### 예상 결과

- 지원자 목록에서 승인을 한 뒤에 팀원이 되어야

#### 심각도

8 / 10

**Comment by weejihye** [comment]
네네! 백엔드 내부에서 데이터 구조가 바뀌면서 팀원 리스트를 반환할때 approved 여부를 필터링 해야 하는데 그 부분이 누락되어 생긴 문제로 보입니다~ 픽스 하겠습니다~

**Comment by weejihye** [comment]
픽스 종료되었습니다. 이슈 닫겠습니다~
