### ISSUE TITLE
[BUG] 소켓 연결 중 오류

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Backend#592]
#### 문제 상황

- 소켓 연결 중 query를 붙이니 접속 url에 각종 param들이 따로 붙습니다.
<img width="1436" alt="스크린샷 2024-01-12 오후 4 20 37" src="https://github.com/peer-42seoul/Peer-Backend/assets/54823522/7e547dda-8997-4a1c-9d0e-8e0576d9a412">

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 사전 조건 (ex. 로그인 여부)

로그인 후 팀 설정 페이지로 입장

#### 재현 절차

socket.io whoAmI 이벤트 사용 중 터집니다.

#### 심각도

8 / 10

**Comment by Paul2021-R** [comment]
해결 완료
