### ISSUE TITLE
[BUG] 관심리스트 스터디 담기 작동 안함

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Backend#626]
#### 문제 상황
관심리스트 스터디 담기 작동 안함

#### 테스트 환경

- OS(mac / ipad / android...) : Mac
- 웹 브라우저 : chrome

#### 사전 조건 (ex. 로그인 여부)
로그인 필수

#### 재현 절차
메인페이지 스터디 탭에서 하트를 누른 이후 새로고침을 합니다.

#### 예상 결과
하트가 그대로 켜져있습니다.

#### 실제 결과
하트가 꺼집니다.

#### 심각도
중

**Comment by weejihye** [comment]
현재 db에는 해당 담기 기능이 동작하고 있는 것으로 보입니다.
하트가 꺼지는 부분은 프론트에서 처리해야 할 사항으로 보입니다.
해당 부분을 프론트에서 수정하기 위해 필요한 조치가 있다면 추가로 요청 부탁드립니다.

**Comment by weejihye** [comment]
@SaltySalt77 해당 수정부분 merge 완료 하였습니다.

**Comment by SaltySalt77** [comment]
완료하여 이슈 닫습니다~
