### ISSUE TITLE
[BUG] 쇼케이스 리스트뷰에서 이미지가 null로 보내지는 버그

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Backend#675]
#### 문제 상황

메인 화면에서 쇼케이스를 누르면 이미지가 제대로 보이지 않는 버그 발생

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 사전 조건 (ex. 로그인 여부)

로그인 여부 필요없음

#### 심각도

8 / 10

**Comment by weejihye** [comment]
@HiHoi  해당 이슈 수정되었습니다.
