### ISSUE TITLE
[BUG] 모집글 긴 내용의 글 입력 시 500에러

### ISSUE THREAD

**Issue by SaltySalt77** [peer-42seoul/Peer-Backend#728]
#### 문제 상황
긴 내용의 글 (200자는 되는데 300자는 안됨. 그 사이는 테스트 x) 입력시 500에러가 발생합니다. 

#### 테스트 환경

- OS(mac / ipad / android...) : 관련 없음
- 웹 브라우저 : 관련 없음

#### 사전 조건 (ex. 로그인 여부)
로그인 함 

#### 재현 절차
모집글에서 아주 긴 글을 작성합니다.

#### 예상 결과
글이 작성 되거나, 작성되지 않는 원인을 알려줍니다.

#### 실제 결과
해당 리스폰스가 뜹니다.
```
could not execute statement;SQL[
    n/a
];nested exception is org.hibernate.exception.DataException: could not execute statement
```

**Comment by weejihye** [comment]
완료!
