### ISSUE TITLE
[BUG] 모집글 쓰기 500

### ISSUE THREAD

**Issue by HiHoi** [peer-42seoul/Peer-Backend#779]
#### 문제 상황

![스크린샷 2024-02-05 오전 10 19 07](https://github.com/peer-42seoul/Peer-Backend/assets/54823522/e1155a3a-0b50-4692-bc37-9ad18efabb83)

모집글 쓰고 저장하는 버튼을 누르면 500

could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement

#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

#### 사전 조건 (ex. 로그인 여부)

로그인 O
프로젝트를 만드는 상황

#### 심각도

10 / 10

**Comment by weejihye** [comment]
본문 길이제한으로 인함. 해결 되었습니다. @HiHoi 확인해주세요~
