### ISSUE TITLE
[J-TB] 팀 해산을 하더라도 그 팀의 모집글이 남아있음.

### ISSUE THREAD

**Issue by joonseong11** [peer-42seoul/Peer-Backend#784]
#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by weejihye** [comment]
모집 종료 프로세스가 없어서 생기는 문제라서 추가 논의가 필요합니다.

**Comment by weejihye** [comment]
일단 팀 status가 바뀌는 지점에  recruit도 바뀌도록 코드 추가해 두었습니다. 추후 status 변경 부분 로직 다시 논의하면 좋겠습니다.

**Comment by weejihye** [comment]
반영되었습니다.
