### ISSUE TITLE
[1.0.1/로그인] 어드민 로그인 후 일반 로그인 오류

### ISSUE THREAD

**Issue by weejihye** [peer-42seoul/Peer-Backend#806]
#### 문제 상황
어드민 로그인 후 일반 로그인시 오류

#### 테스트 환경
- OS(mac / ipad / android...) :mac
- 웹 브라우저 :chrome

#### 사전 조건 (ex. 로그인 여부)
어드민 로그인 직후

#### 재현 절차
쿠키가 비어있는 상태에서 어드민 로그인 후 일반 로그인 시도

#### 예상 결과
로그인이 잘 되면 좋겠다~

#### 실제 결과
오류가 납니다.

#### 심각도
2/10(일시적인 해결 방법은 존재하기 때문에)

**Comment by sinryuji** [comment]
해결 완료
