### ISSUE TITLE
[BUG] 모집글 자유게시판에 공지사항이라고 표기 오류.

### ISSUE THREAD

**Issue by wochae** [peer-42seoul/Peer-Backend#868]
#### 문제 상황
모바일 화면에서 자유 게시판에 작성된 글 상단을 보면
![image](https://github.com/peer-42seoul/Peer-Backend/assets/101040879/7dd6143b-a862-4ddd-8d49-1f195e46976f)
공지사항이라고 뜸..
#### 테스트 환경

- OS(mac / ipad / android...) :
- 웹 브라우저 :

**Comment by yoouyeon** [comment]
이슈 제보 감사합니당 프론트에서만 수정하면 해결될 문제일 것 같아 동일한 이슈 프론트에 만들고 이 이슈는 닫을게요!
