### ISSUE TITLE
[Question] 쪽지 기능에 대한 의문

### ISSUE THREAD

**Issue by BlitzCoding** [peer-42seoul/Peer-Backend#9]
- 쪽지 차단 기능 여부
- 쪽지 삭제 여부 (나만 삭제, 다른 사람도 못보게 삭제)
- 쪽지 수정 여부
- 쪽지에 사진이나 파일 넣을 수 있는가?
- 쪽지를 읽었는지 안읽었는지 여부를 확인할 수 있어야하는가?
- 쪽지당 고유키가 필요한가?

**Comment by Paul2021-R** [comment]
### 쪽지 기능에 대한 의문
개요 : 기본적으로 기획에 있지 않은 내용은 작성되지 않음을 전제로 한다. 

- 쪽지 차단 기능 여부 
A: 당장은 기능 자체 구현을 우선적으로 진행함 

- 쪽지 삭제 여부 (나만 삭제, 다른 사람도 못보게 삭제) 
A: 해당 기능 역시 우선적으로 진행할 예정 없으며, 향후 업데이트도 고려하진 않음. 

- 쪽지 수정 여부
A: 향후 가능성은 있음(제한시간을 두는 등의 제약이 있음) 단, 소켓으로 구성되야할 필요가 있을 수 있음.

- 쪽지에 사진이나 파일 넣을 수 있는가?
A: 쪽지는 당장의 간단한 연락 이상으로 할 생각 없음. 

- 쪽지를 읽었는지 안읽었는지 여부를 확인할 수 있어야하는가?
A: 내부적으로 확인 여부를 넣으면 좋지만, 개발 강도에 따라 확인할 것. (사실 구현 자체는 어렵지 않으니 가능은 하지만 '쪽지' 라는 컨셉 상의 문제, 소켓이아닌 HTTP 방식의 단점등으로 굳이 해야 하는지 의문

- 쪽지당 고유키가 필요한가?
A: 현재 기획에서 필요할 이유가 없음. 그러나 고유키가 필요하다고 생각한 이유를 먼저 듣고 싶음
